### ISSUE TITLE
Ability to list transactions by contact

### ISSUE THREAD

**Issue by mathewparet** [up-banking/api#106]
It would be nice to have an API to list transactions by contact. So I can list all transactions made to/from a contact and make a report.

**Comment by johnmee** [comment]
You're effectively asking for another filter on the transactions.  But filter by which field exactly do you have in mind?
There is no concrete attribute which identifies the other party.

"description", or "message", are free text fields from which you have to take a fuzzy guess as to where the money came/went.  I expect this is a weakness in the banking system rather than the upbank api.

https://developer.up.com.au/#get_transactions

**Comment by mathewparet** [comment]
It is ok even if I am not able to filter based on the description. But it would be nice to be able to list all transactions by contact via API. I am trying to generate a PDF report of all transactions I've made to a particular contact.

**Comment by johnmee** [comment]
Doesn't hurt to ask. 

I expect you'd do better to 'get' all your transactions then filter and post-process them locally.
Maybe [zq](https://zed.brimdata.io/docs/tutorials/zq/) or [jq](https://stedolan.github.io/jq/) will be your friend.

**Comment by johnmee** [comment]
Sorry. Me again. 
It occurs to me that this could be framed as a feature request, not for another Transaction 'filter', but a Transaction 'Search': ie 'Find all transactions with <searchterm>'; in this case the search term is the contact's name.

And, whilst a feature of the app, Search is completely missing from the API.
