### ISSUE TITLE
For all related links, include an id and type field

### ISSUE THREAD

**Issue by Hona** [up-banking/api#75]
In the case of API wrapper libraries, it is painful to just use the URL, it would be nice to have an ID field, and type to provide more concrete info on the related data

**Comment by d11wtq** [comment]
@Hona I'm not sure if it's the same as what you're asking, but we do include `id` and `type` in the `data` field on most to-one relationships. For to-many relationships we generally omit the `data` field because it's not possible to paginate it on very large data sets (e.g. accounts -> transactions).

If you look, for example, as the `/transactions` endpoint (https://developer.up.com.au/#get_transactions_id):

```
  "relationships": {
    "account": {
        "data": {
          "type": "accounts",
          "id": "d8487aaa-bd2f-4f4a-8d79-ae24c8b853ab"
        },
        "links": {
          "related": "https://api.up.com.au/api/v1/accounts/d8487aaa-bd2f-4f4a-8d79-ae24c8b853ab"
        }
      }
  }
```

If you were to look at the inverse of that relationship, however, we don't include the `data` field because accounts can have hundreds of thousands of transactions.

**Comment by d11wtq** [comment]
Gonna close this one for now given no response, but sing out of the response didn't satisfy your question @Hona.
