### ISSUE TITLE
How to determine the Account Balances at historical date/times?

### ISSUE THREAD

**Issue by johnmee** [up-banking/api#78]
This is a Feature Request for the determination of the balance of an account at a specific date/time.

The tranactions list `/transactions` returns in a long list without any account balance numbers.  When one is importing into an accounting program, it is very helpful to be able to **reconcile** account balances periodically to detect errors and inadvertent bookentry postings.  However, the only balance check I can find is the current balance provided by `/accounts`.

Option A,  as seen in the westpac/stgeorge transaction listings, the residual account balance is included as a data point with _every_ transaction.

Option B is the addition of a ISO formatted date/time parameter to `/accounts` which returns the state, and balance, of the account/s on the given date/time.  I expect consideration of the exact moment in time could complicate things.  A compromise to a fixed time of day, eg midnight UTC, or timezone param, would be reasonable.  This option may be relevant to the feature request for [deleted/removed accounts](https://github.com/up-banking/api/issues/55).

I am just looking for a way to reconcile my account balances against yours at intermediate points during an import.

**Comment by d11wtq** [comment]
This is actually a bit tricky because Up uses the account's available balance, which takes into account pending transactions and can change in response to pending transactions being deleted or settled at a different amount. Essentially if you had a running balance on your 7-11 transaction today, that might be a different running balance in 2 weeks time, if something like a hotel room deposit hold that was placed 3 days prior is subsequently deleted.

**Comment by johnmee** [comment]
I'll take whatever "balance" you have.  
Is the current "available balance" all you keep?

**Comment by all64bits** [comment]
I am also interested in this. Would it possible to get a running balance for each settled transaction, and just return null for pending transactions? That way, the balance shouldn't change when pending transactions settle?

**Comment by all64bits** [comment]
I understand what you say @d11wtq about the impact on balance assertions caused by changes to pending transactions which are sitting earlier in the list. This is the same issue I have when exporting transaction info for a credit account I have. However I also have a transactions account with the same bank, and when I export the transaction list from that one, it only includes pending transactions *after* they settle, and the balance assertions never change.

**Comment by d11wtq** [comment]
Perhaps it may be sufficient to add `?sort=-createdAt` (default), `?sort=settledAt` (`?sort=-settledAt` for descending order, as per JSON:API). The `filter[since]` and `filter[until]` parameters would operate on the basis of the sort order.

The only question that then arises is what to do about `null` values for `settledAt` in the case of pending transactions. Likely the best option would be to surface them either always at the start or always at the end, or perhaps make it such that using `?sort=settledAt` implies `?filter[status]=SETTLED` (I think I prefer keeping it explicit though).

**Comment by johnmee** [comment]
My other bank deals with this "whats my current balance" question by recording the transactions with the settlement timestamp.  They include a timestamp of when the transaction actually took place in the transaction description.

But it looks like this is a "wont fix" :-/  

I'm still keen for a solution to this "what was the balance" question.  Sometimes it takes me a looong time to get around to importing transactions.  Which puts me in a lot of pain when I'm hunting through 6 months worth of transactions to find whatever is throwing out the reconciliation.
