### ISSUE TITLE
RFC-3339 formatted date being rejected as a filter

### ISSUE THREAD

**Issue by roscom** [up-banking/api#96]
I am applying a filter on GET /transactions as in:
```
curl -s https://api.up.com.au/api/v1/accounts<account number ref>/transactions                
 -H 'Authorization: Bearer up:yeah:<authorization code>'                 
-G                 
-d 'filter[since]=2021-11-15T16:01:01+11:00'\n               
"
```
This is being rejected with the message:
```
:errors => [
        [0] {
            :status => "400",
             :title => "Invalid Parameter",
            :detail => "invalid date-time value (must be rfc-3339)",
            :source => {
                :parameter => "filter[since]"
            }
        }
    ]
```
The date in the get command appears to be RFC-3339 EXACTLY correct.
Could you please clarify.

**Comment by d11wtq** [comment]
You need to URL-encode the `+` as `%2B` otherwise it comes through as a space.

**Comment by roscom** [comment]
Thank you. That solved the 400 error.
I note that this parameter (as well as filter[until]) doesn't play with pagination.
However, using a filter[since] of 3 months ago only returns the most recent 20 results when there are many more, and to get additional results it seems that the page[size] must be up'd (to a max of 100)
Documentation is unclear on this. Could you please confirm or clarify?

**Comment by d11wtq** [comment]
🙇 Glad you got moving. In terms of pagination, as you say, you don't want to increment the `filter[since]` to work through pages. Rather, you should follow the pagination links from the `links` section of the response, which will retain any filters you have used in the initial request.

https://developer.up.com.au/#pagination

Apologies, the examples in the documentation for List Transaction don't include pagination links, but you can see any example response that does include pagination links for List Accounts: https://developer.up.com.au/#get_accounts

**Comment by d11wtq** [comment]
To clarify, parse the JSON response, extract `response -> links -> next`, the re-request that URL to get the next page. Continue until `response -> links -> next` is `null`.

**Comment by roscom** [comment]
Thank you. Understood. 
To clarify, I don't want to use pagination, I just wanted all of the transactions between filter[since] up to the present time.
If I don't set the page[size] parameter I'll only get the most recent 20 it seems. But page[size] is limted to 100. There may be more.
I would have thought I'd receive the number of transactions between the filter[since] date and now.
Have I got that right?

**Comment by d11wtq** [comment]
> I would have thought I'd receive the number of transactions between the filter[since] date and now.
Have I got that right?

:100: you're correct, there is a hard-limit of 100 records per page, which you can control via `page[size]`. Unfortunately we can't allow arbitrarily large page sizes because generating arbitrarily large amounts of JSON also requires arbitrarily large amounts of server resources. The 100 may change to something greater in the future, but there'll always be a cap due to the implications of not having a cap.
