### ISSUE TITLE
Confirmation of Spending/2up in Transaction Data

### ISSUE THREAD

**Issue by all64bits** [up-banking/api#97]
As per [this closed issue](https://github.com/up-banking/api/issues/84#issuecomment-921511066) we have transactional data for the 2up account available via the API. However, in the documentation, I can't find the "display_name" field (mentioned in the above link).

I'm keen to get transactional data and have confirmation per transaction if it is sitting in the "Spending" account or the "2up Spending" account. I'm not sure if I'm missing something.

**Comment by d11wtq** [comment]
@all64bits it looks like `display_name` was a typo on that other issue sorry. It's actually called `displayName`.

https://developer.up.com.au/#get_accounts

That said, we should probably add a proper enum field to distinguish 2Up accounts from Up accounts. Stay tuned...

**Comment by all64bits** [comment]
@d11wtq thanks for clarifying. Look forward to the addition of such a field in the Transactions query. In the meantime I think I will try to pull in separate transaction lists for my account and my wife's account, and I expect I will be able to infer the 2up transactions by comparing the two.

**Comment by d11wtq** [comment]
You should easily be able to identify transactions for 2Up vs Up by fetching transactions based on the account, rather than all at once.

https://developer.up.com.au/#get_accounts_accountId_transactions

If you do fetch them all at once, you can also group them by account by first fetching the list of accounts from https://developer.up.com.au/#accounts in order to get their IDs + display names, and then fetching all transactions from https://developer.up.com.au/#transactions and using the account ID from the `relationships` in order to group them manually.

You can only fetch your own transactions and your 2Up transactions via the API, but not your Player 2's personal transactions.

**Comment by d11wtq** [comment]
@all64bits just a heads-up that we're adding `ownershipType` (with values `INDIVIDUAL` or `JOINT`) to the account data and we're also adding a `?filter[ownershipType]=JOINT` so you can scope to Up vs 2Up explicitly. This should be released on Monday.

**Comment by d11wtq** [comment]
We've now released the change in relation to exposing `ownershipType`:

https://developer.up.com.au/#get_accounts

Hopefully this makes working with Up vs 2Up easier.

**Comment by all64bits** [comment]
@d11wtq thanks for the responsiveness on this issue, this will be very helpful with my scripts!
