### ISSUE TITLE
Filter[since] on settledAt

### ISSUE THREAD

**Issue by bentwonk** [up-banking/api#98]
When getting the transactions using the filter[since] is is possible to filter on the settledAt date, not createdAt as I am only interested once a transaction has been settled.

**Comment by d11wtq** [comment]
Hi @bentwonk,

I'm not sure if this will help you or not, but you can use `filter[status]` to get only the settled transactions, but `filter[since]` would still search on the `createdAt`, yep. Up rarely exposes the times at which transactions settle and favours keeping transactions ordered as they first occurred.

**Comment by bentwonk** [comment]
Thanks, but i don't think that will help,
a createdAt transaction is in a nebulas state and may never be settled, so I don't want to account for it until settlement.

 I want to automatically pull down the transactions aprox weekly, I  don't want to pull down duplicates, so was using the date to slice the data, but currently being limited to filtering on createsAt it's possible to get a transaction that was created but not settled in one slice, and it will not appear in the next weekly slice.  I am thinking my solution is to store all the transactions, then test each HELD transaction against the api to see if its been settled since the original data was grabbed.   Seems messy compared to just filtering on settledAt :-(
